from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path
from typing import Any, cast

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_INPUT = ROOT / "openapi" / "market-monitor-v1.yaml"
DEFAULT_OUTPUT = ROOT / "apps" / "web" / "src" / "api" / "generated.ts"
HTTP_METHODS = ("get", "post", "put", "patch", "delete")
IDENTIFIER = re.compile(r"^[A-Za-z_$][A-Za-z0-9_$]*$")


def load_contract(path: Path) -> dict[str, Any]:
    value: Any = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(value, dict):
        raise ValueError("OpenAPI document must be a JSON object")
    return cast(dict[str, Any], value)


def render_types(contract: dict[str, Any]) -> str:
    components = _object(contract.get("components"), "components")
    schemas = _object(components.get("schemas"), "components.schemas")
    operations = _operations(contract)
    operation_ids = [operation_id for _, _, operation_id, _, _ in operations]
    if len(operation_ids) != len(set(operation_ids)):
        raise ValueError("OpenAPI operationId values must be unique")

    lines = [
        "// Generated by scripts/generate_api_types.py from openapi/market-monitor-v1.yaml.",
        "// Do not edit by hand or add product behavior here.",
        "",
    ]
    for name, schema in schemas.items():
        if not IDENTIFIER.fullmatch(name):
            raise ValueError(f"component schema is not a TypeScript identifier: {name}")
        prefix = f"export type {name} ="
        rendered = _ts_type(
            contract,
            _object(schema, f"schema {name}"),
            0,
            prefix_length=len(prefix) + 2,
        )
        lines.extend((f"{prefix}{_type_separator(rendered)}{rendered};", ""))

    lines.extend(("export interface components {", "\tschemas: {"))
    for name in schemas:
        lines.append(f"\t\t{_property_name(name)}: {name};")
    lines.extend(("\t};", "}", ""))

    lines.append("export interface OperationRequests {")
    for path, method, operation_id, path_item, operation in operations:
        del path, method
        parameters = [
            *_parameter_list(path_item.get("parameters")),
            *_parameter_list(operation.get("parameters")),
        ]
        lines.append(f"\t{_property_name(operation_id)}: {{")
        for location in ("path", "query", "header", "cookie"):
            selected = [
                _resolve(contract, parameter)
                for parameter in parameters
                if _resolve(contract, parameter).get("in") == location
            ]
            parameter_type = _parameter_type(contract, selected, 2) if selected else "never"
            lines.append(f"\t\t{location}: {parameter_type};")
        request_body_value = operation.get("requestBody")
        if request_body_value is None:
            lines.append("\t\tbody: never;")
        else:
            request_body = _resolve(
                contract, _object(request_body_value, f"{operation_id}.requestBody")
            )
            body_type = _content_type(contract, request_body.get("content"), 2)
            optional = "" if request_body.get("required") is True else "?"
            lines.append(f"\t\tbody{optional}: {body_type};")
        lines.append("\t};")
    lines.extend(("}", ""))

    lines.append("export interface OperationResponses {")
    for _, _, operation_id, _, operation in operations:
        responses = _object(operation.get("responses"), f"{operation_id}.responses")
        lines.append(f"\t{_property_name(operation_id)}: {{")
        for status, response_value in responses.items():
            response = _resolve(
                contract, _object(response_value, f"{operation_id}.responses.{status}")
            )
            lines.append(f"\t\t{_property_name(status)}: {{")
            header_values = response.get("headers")
            if header_values is None:
                lines.append("\t\t\theaders: never;")
            else:
                headers = _object(header_values, f"{operation_id}.responses.{status}.headers")
                lines.append(f"\t\t\theaders: {_headers_type(contract, headers, 3)};")
            body_type = _content_type(contract, response.get("content"), 3, missing="never")
            lines.extend((f"\t\t\tbody: {body_type};", "\t\t};"))
        lines.append("\t};")
    lines.extend(("}", ""))

    lines.append("export interface ApiOperations {")
    for path, method, operation_id, _, _ in operations:
        lines.extend(
            (
                f"\t{_property_name(operation_id)}: {{",
                f"\t\tmethod: {json.dumps(method.upper())};",
                f"\t\tpath: {json.dumps(path)};",
                f"\t\trequest: OperationRequests[{json.dumps(operation_id)}];",
                f"\t\tresponses: OperationResponses[{json.dumps(operation_id)}];",
                "\t};",
            )
        )
    lines.extend(("}", ""))

    paths: dict[str, list[tuple[str, str]]] = {}
    for path, method, operation_id, _, _ in operations:
        paths.setdefault(path, []).append((method, operation_id))
    lines.append("export interface ApiPaths {")
    for path, path_operations in paths.items():
        lines.append(f"\t{json.dumps(path)}: {{")
        for method, operation_id in path_operations:
            lines.append(
                f"\t\t{_property_name(method)}: ApiOperations[{json.dumps(operation_id)}];"
            )
        lines.append("\t};")
    lines.extend(("}", ""))
    return "\n".join(lines)


def check_generated_types(root: Path) -> str | None:
    source = root / "openapi" / "market-monitor-v1.yaml"
    target = root / "apps" / "web" / "src" / "api" / "generated.ts"
    if not source.is_file() or not target.is_file():
        return None
    try:
        expected = render_types(load_contract(source))
    except (OSError, ValueError, json.JSONDecodeError) as error:
        return f"generated API types check failed: {error}"
    if target.read_text(encoding="utf-8") != expected:
        return "generated API types are stale; run: python scripts/generate_api_types.py"
    return None


def _operations(
    contract: dict[str, Any],
) -> list[tuple[str, str, str, dict[str, Any], dict[str, Any]]]:
    paths = _object(contract.get("paths"), "paths")
    result: list[tuple[str, str, str, dict[str, Any], dict[str, Any]]] = []
    for path, path_item_value in paths.items():
        path_item = _object(path_item_value, f"path {path}")
        for method in HTTP_METHODS:
            operation_value = path_item.get(method)
            if operation_value is None:
                continue
            operation = _object(operation_value, f"{method.upper()} {path}")
            operation_id = operation.get("operationId")
            if not isinstance(operation_id, str) or not operation_id:
                raise ValueError(f"{method.upper()} {path} must have operationId")
            result.append((path, method, operation_id, path_item, operation))
    return result


def _resolve(contract: dict[str, Any], value: dict[str, Any]) -> dict[str, Any]:
    seen: set[str] = set()
    while "$ref" in value:
        reference = value["$ref"]
        if not isinstance(reference, str) or not reference.startswith("#/"):
            raise ValueError(f"only local OpenAPI references are supported: {reference!r}")
        if reference in seen:
            raise ValueError(f"cyclic OpenAPI reference: {reference}")
        seen.add(reference)
        target: Any = contract
        for part in reference[2:].split("/"):
            target = _object(target, reference)[part.replace("~1", "/").replace("~0", "~")]
        value = _object(target, reference)
    return value


def _ts_type(
    contract: dict[str, Any],
    schema: dict[str, Any],
    level: int,
    *,
    prefix_length: int = 0,
) -> str:
    if "$ref" in schema:
        reference = schema["$ref"]
        if not isinstance(reference, str) or not reference.startswith("#/components/schemas/"):
            raise ValueError(f"unsupported schema reference: {reference!r}")
        return reference.rsplit("/", 1)[-1]
    if "const" in schema:
        return _literal(schema["const"])
    if "enum" in schema:
        enum = schema["enum"]
        if not isinstance(enum, list) or not enum:
            raise ValueError("schema enum must be a non-empty array")
        return _union([_literal(item) for item in enum], level, prefix_length=prefix_length)
    for keyword, separator in (("anyOf", " | "), ("oneOf", " | "), ("allOf", " & ")):
        values = schema.get(keyword)
        if values is not None:
            if not isinstance(values, list) or not values:
                raise ValueError(f"schema {keyword} must be a non-empty array")
            rendered_parts = [
                _ts_type(contract, _object(item, f"schema.{keyword}"), level) for item in values
            ]
            return (
                _union(rendered_parts, level, prefix_length=prefix_length)
                if separator == " | "
                else separator.join(rendered_parts)
            )

    schema_type = schema.get("type")
    if isinstance(schema_type, list):
        return _union(
            [_primitive_type(item) for item in schema_type],
            level,
            prefix_length=prefix_length,
        )
    if schema_type == "array":
        items = _object(schema.get("items"), "array.items")
        item_type = _ts_type(contract, items, level)
        return f"Array<{item_type}>"
    if schema_type == "object" or "properties" in schema or "additionalProperties" in schema:
        properties_value = schema.get("properties", {})
        properties = _object(properties_value, "object.properties")
        additional = schema.get("additionalProperties")
        if not properties:
            if isinstance(additional, dict):
                return f"Record<string, {_ts_type(contract, additional, level)}>"
            return "Record<string, unknown>"
        required_value = schema.get("required", [])
        if not isinstance(required_value, list) or not all(
            isinstance(item, str) for item in required_value
        ):
            raise ValueError("object.required must be an array of strings")
        required = set(cast(list[str], required_value))
        lines = ["{"]
        for name, child in properties.items():
            optional = "" if name in required else "?"
            prefix = f"{_indent(level + 1)}{_property_name(name)}{optional}:"
            rendered = _ts_type(
                contract,
                _object(child, f"property {name}"),
                level + 1,
                prefix_length=_display_width(prefix) + 2,
            )
            lines.append(f"{prefix}{_type_separator(rendered)}{rendered};")
        lines.append(f"{_indent(level)}}}")
        return "\n".join(lines)
    if schema_type is None:
        return "unknown"
    return _primitive_type(schema_type)


def _parameter_type(contract: dict[str, Any], parameters: list[dict[str, Any]], level: int) -> str:
    lines = ["{"]
    for parameter in parameters:
        name = parameter.get("name")
        if not isinstance(name, str):
            raise ValueError("parameter name must be a string")
        optional = "" if parameter.get("required") is True else "?"
        schema = _object(parameter.get("schema"), f"parameter {name}.schema")
        prefix = f"{_indent(level + 1)}{_property_name(name)}{optional}:"
        rendered = _ts_type(
            contract,
            schema,
            level + 1,
            prefix_length=_display_width(prefix) + 2,
        )
        lines.append(f"{prefix}{_type_separator(rendered)}{rendered};")
    lines.append(f"{_indent(level)}}}")
    return "\n".join(lines)


def _headers_type(contract: dict[str, Any], headers: dict[str, Any], level: int) -> str:
    lines = ["{"]
    for name, header_value in headers.items():
        header = _resolve(contract, _object(header_value, f"response header {name}"))
        schema = _object(header.get("schema"), f"response header {name}.schema")
        prefix = f"{_indent(level + 1)}{_property_name(name)}:"
        rendered = _ts_type(
            contract,
            schema,
            level + 1,
            prefix_length=_display_width(prefix) + 2,
        )
        lines.append(f"{prefix}{_type_separator(rendered)}{rendered};")
    lines.append(f"{_indent(level)}}}")
    return "\n".join(lines)


def _content_type(
    contract: dict[str, Any], value: Any, level: int, *, missing: str = "unknown"
) -> str:
    if value is None:
        return missing
    content = _object(value, "content")
    media = content.get("application/json")
    if media is None:
        raise ValueError("only application/json content is supported")
    media_value = _object(media, "content.application/json")
    schema = _object(media_value.get("schema"), "content.application/json.schema")
    return _ts_type(contract, schema, level)


def _parameter_list(value: Any) -> list[dict[str, Any]]:
    if value is None:
        return []
    if not isinstance(value, list):
        raise ValueError("operation parameters must be an array")
    return [_object(item, "operation parameter") for item in value]


def _object(value: Any, name: str) -> dict[str, Any]:
    if not isinstance(value, dict):
        raise ValueError(f"{name} must be an object")
    return cast(dict[str, Any], value)


def _primitive_type(value: Any) -> str:
    mapping = {
        "string": "string",
        "integer": "number",
        "number": "number",
        "boolean": "boolean",
        "null": "null",
        "object": "Record<string, unknown>",
    }
    if value not in mapping:
        raise ValueError(f"unsupported JSON Schema type: {value!r}")
    return mapping[value]


def _literal(value: Any) -> str:
    if value is None:
        return "null"
    if value is True:
        return "true"
    if value is False:
        return "false"
    if isinstance(value, (str, int, float)):
        return json.dumps(value, ensure_ascii=False)
    raise ValueError(f"unsupported enum/const value: {value!r}")


def _union(parts: list[str], level: int, *, prefix_length: int = 0) -> str:
    compact = " | ".join(parts)
    if all("\n" not in part for part in parts) and prefix_length + len(compact) <= 80:
        return compact
    return "\n" + "\n".join(f"{_indent(level + 1)}| {part}" for part in parts)


def _property_name(value: str) -> str:
    return value if IDENTIFIER.fullmatch(value) else json.dumps(value, ensure_ascii=False)


def _indent(level: int) -> str:
    return "\t" * level


def _display_width(value: str) -> int:
    return len(value.expandtabs(2))


def _type_separator(rendered: str) -> str:
    return "" if rendered.startswith("\n") else " "


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate TypeScript from the source OpenAPI")
    parser.add_argument("--input", type=Path, default=DEFAULT_INPUT)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--check", action="store_true")
    arguments = parser.parse_args()
    try:
        rendered = render_types(load_contract(arguments.input))
    except (OSError, ValueError, json.JSONDecodeError) as error:
        print(f"ERROR: {error}", file=sys.stderr)
        return 1
    if arguments.check:
        if (
            not arguments.output.is_file()
            or arguments.output.read_text(encoding="utf-8") != rendered
        ):
            print(
                "ERROR: generated API types are stale; run: python scripts/generate_api_types.py",
                file=sys.stderr,
            )
            return 1
        print("generated API types are current")
        return 0
    arguments.output.parent.mkdir(parents=True, exist_ok=True)
    arguments.output.write_text(rendered, encoding="utf-8", newline="\n")
    print(f"generated {arguments.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
