// Generated by scripts/generate_api_types.py from openapi/market-monitor-v1.yaml.
// Do not edit by hand or add product behavior here.

export type StableUid = string;

export type Rfc3339Time = string;

export type CalendarDate = string;

export type Ratio = number;

export type DecimalString = string;

export type OpaqueCursor = string;

export type ETagValue = string;

export type ValueStatus =
	| "VALUE"
	| "MISSING"
	| "NOT_APPLICABLE"
	| "STALE"
	| "INVALID";

export type AvailabilityState =
	| "AVAILABLE"
	| "WARMING_UP"
	| "SUSPENDED"
	| "UNAVAILABLE";

export type LifecycleState =
	| "OBSERVING"
	| "STARTING"
	| "EXPANDING"
	| "ACCELERATING"
	| "DIVERGING"
	| "DECLINING";

export type DataHealthStatus = "HEALTHY" | "DEGRADED" | "UNHEALTHY" | "UNKNOWN";

export type FitnessStatus =
	| "FIT"
	| "FIT_WITH_LIMITATIONS"
	| "UNFIT"
	| "UNKNOWN";

export type EvidenceSufficiency = "LOW" | "MEDIUM" | "HIGH" | "UNKNOWN";

export type GuardianEffect =
	| "ALLOW"
	| "ALLOW_WITH_WARNING"
	| "DOWNGRADE"
	| "SUPPRESS"
	| "PAUSE";

export type EventStatus = "CANDIDATE" | "ACTIVE" | "RESOLVED" | "INVALIDATED";

export type DeliveryStatus =
	| "PENDING"
	| "PROCESSING"
	| "RETRY_WAIT"
	| "DELIVERED"
	| "FAILED"
	| "CANCELLED"
	| "EXPIRED";

export type HealthLiveView = {
	service: "market-monitor";
	status: "ok";
};

export type SystemHealthSummaryView = {
	status: string;
	database_readable: boolean;
	migration_current: boolean;
	migration_revision: string;
	recovery_state: string;
	restore_generation: number;
};

export type CapabilityHealthView = {
	report_uid: StableUid;
	epoch_uid: StableUid;
	capability: string;
	health: DataHealthStatus;
	fitness: FitnessStatus;
	coverage: Ratio;
	latency_ms: number;
	observed_at: Rfc3339Time;
	valid_until: Rfc3339Time;
	expired: boolean;
};

export type CapabilityListView = {
	items: Array<CapabilityHealthView>;
};

export type EnumRegistryView = Record<string, Array<string>>;

export type CodeView = {
	group: string;
	code: string;
	meaning: string;
	active: 0 | 1;
};

export type CodeListView = {
	items: Array<CodeView>;
};

export type ConfidenceView = {
	level: "HIGH" | "MEDIUM" | "LOW" | "BLOCKED";
	reference_status:
		| "NORMAL_REFERENCE"
		| "LIMITED_REFERENCE"
		| "OBSERVATION_ONLY"
		| "NO_JUDGMENT";
};

export type EvidenceItemView = {
	role: "SUPPORTING" | "CONTRARY";
	reason_code: string;
	fact_uid: StableUid | null;
	fact_uid_status: ValueStatus;
	rule_execution_uid: StableUid | null;
	rule_execution_uid_status: ValueStatus;
	template_key: string;
	attributes: Record<string, string>;
};

export type GuardianView = {
	status: "NORMAL" | "CAUTION" | "WARNING" | "BLOCKED";
	effect: GuardianEffect;
	blocking: boolean;
	reasons: Array<EvidenceItemView>;
};

export type ScoutView = {
	status: "NONE" | "OBSERVING" | "ACTIVE";
	strength: "LOW" | "MEDIUM" | "HIGH";
	suppressed_by_guardian: boolean;
	reasons: Array<EvidenceItemView>;
};

export type ExplanationView = {
	supporting: Array<EvidenceItemView>;
	contrary: Array<EvidenceItemView>;
};

export type DataLimitationView = {
	code: string;
	detail: string;
};

export type DataQualityView = {
	health: DataHealthStatus;
	fitness: FitnessStatus;
	evidence_sufficiency: EvidenceSufficiency;
	coverage: Ratio;
	limitations: Array<DataLimitationView>;
};

export type LastValidStateView = {
	lifecycle_state: LifecycleState | null;
	as_of_time: Rfc3339Time | null;
	value_status: ValueStatus;
};

export type MarketSourceView = {
	evaluation_uid: StableUid;
	snapshot_uid: StableUid;
	guardian_uid: StableUid;
	scout_uid: StableUid;
	projection_version: number;
};

export type MarketView = {
	subject_uid: StableUid;
	availability_state: AvailabilityState;
	lifecycle_state: LifecycleState | null;
	lifecycle_value_status: ValueStatus;
	as_of_time: Rfc3339Time;
	confidence: ConfidenceView;
	guardian: GuardianView;
	scout: ScoutView;
	explanation: ExplanationView;
	data_quality: DataQualityView;
	last_valid_state: LastValidStateView;
	source: MarketSourceView;
};

export type InstrumentView = {
	instrument_uid: StableUid;
	instrument_kind: string;
	identity_version_uid: StableUid;
	exchange: string;
	trading_code: string;
	name: string;
	listing_status: string;
	trading_status: string;
	valid_from: Rfc3339Time;
};

export type SectorView = {
	sector_uid: StableUid;
	sector_kind: string;
	sector_version_uid: StableUid;
	name: string;
	valid_from: Rfc3339Time;
	subject_uid: StableUid | null;
	subject_uid_status: ValueStatus;
};

export type SectorMemberView = {
	instrument_uid: StableUid;
	member_role: string;
	membership_version_uid: StableUid;
	trading_date: CalendarDate;
};

export type StateTransitionView = {
	transition_uid: StableUid;
	from_lifecycle_state: LifecycleState | null;
	from_lifecycle_state_status: ValueStatus;
	to_lifecycle_state: LifecycleState;
	evaluation_uid: StableUid;
	occurred_at: Rfc3339Time;
};

export type FactView = {
	fact_uid: StableUid;
	fact_code: string;
	value: DecimalString | null;
	value_status: ValueStatus;
	unit: string;
	as_of_time: Rfc3339Time;
};

export type EventSummaryView = {
	event_uid: StableUid;
	event_version_uid: StableUid;
	subject_uid: StableUid;
	event_kind: string;
	status: EventStatus;
	version: number;
	as_of_time: Rfc3339Time;
	guardian: GuardianView;
	confidence: ConfidenceView;
	scout: ScoutView;
	explanation: ExplanationView;
	data_limitations: Array<DataLimitationView>;
};

export type EventDetailView = {
	event_uid: StableUid;
	event_version_uid: StableUid;
	subject_uid: StableUid;
	event_kind: string;
	status: EventStatus;
	version: number;
	as_of_time: Rfc3339Time;
	created_at: Rfc3339Time;
	guardian: GuardianView;
	confidence: ConfidenceView;
	scout: ScoutView;
	explanation: ExplanationView;
	data_limitations: Array<DataLimitationView>;
};

export type EventVersionView = {
	event_uid: StableUid;
	event_version_uid: StableUid;
	subject_uid: StableUid;
	event_kind: string;
	status: EventStatus;
	version: number;
	as_of_time: Rfc3339Time;
	change_type: string;
	guardian: GuardianView;
	confidence: ConfidenceView;
	scout: ScoutView;
	explanation: ExplanationView;
	data_limitations: Array<DataLimitationView>;
};

export type FrozenRiskView = {
	tag: string;
	severity: string;
	reason_code: string;
	fact_uid: StableUid | null;
	fact_uid_status: ValueStatus;
	rule_execution_uid: StableUid | null;
	rule_execution_uid_status: ValueStatus;
	template_key: string;
	attributes: Record<string, string>;
};

export type FrozenGuardianView = {
	guardian_uid: StableUid;
	effect: GuardianEffect;
	blocking: boolean;
	risks: Array<FrozenRiskView>;
};

export type FrozenScoutTagView = {
	tag: string;
	reason_code: string;
	fact_uid: StableUid | null;
	fact_uid_status: ValueStatus;
	rule_execution_uid: StableUid | null;
	rule_execution_uid_status: ValueStatus;
	template_key: string;
	attributes: Record<string, string>;
};

export type FrozenScoutView = {
	scout_uid: StableUid;
	status: "NONE" | "OBSERVING" | "ACTIVE";
	strength: "LOW" | "MEDIUM" | "HIGH";
	suppressed_by_guardian: boolean;
	tags: Array<FrozenScoutTagView>;
};

export type FrozenEventView = {
	event_uid: StableUid;
	version: number;
	status: EventStatus;
};

export type NotificationFrozenContextView = {
	as_of_time: Rfc3339Time;
	guardian: FrozenGuardianView;
	confidence: ConfidenceView;
	scout: FrozenScoutView;
	explanation: ExplanationView;
	data_limitations: Array<DataLimitationView>;
	event: FrozenEventView;
};

export type NotificationView = {
	intent_uid: StableUid;
	event_version_uid: StableUid;
	channel: string;
	intent_kind: string;
	created_at: Rfc3339Time;
	expires_at: Rfc3339Time;
	delivery_status: DeliveryStatus;
	attempt_count: number;
	frozen_context: NotificationFrozenContextView;
};

export type AuditView = {
	audit_uid: StableUid;
	action: string;
	subject_uid: StableUid | null;
	subject_uid_status: ValueStatus;
	analysis_commit_uid: StableUid | null;
	analysis_commit_uid_status: ValueStatus;
	detail_hash: string;
	created_at: Rfc3339Time;
};

export type InstrumentPage = {
	items: Array<InstrumentView>;
	next_cursor: OpaqueCursor | null;
	next_cursor_status: ValueStatus;
};

export type SectorPage = {
	items: Array<SectorView>;
	next_cursor: OpaqueCursor | null;
	next_cursor_status: ValueStatus;
};

export type SectorMemberPage = {
	items: Array<SectorMemberView>;
	next_cursor: OpaqueCursor | null;
	next_cursor_status: ValueStatus;
};

export type StateTransitionPage = {
	items: Array<StateTransitionView>;
	next_cursor: OpaqueCursor | null;
	next_cursor_status: ValueStatus;
};

export type FactPage = {
	items: Array<FactView>;
	next_cursor: OpaqueCursor | null;
	next_cursor_status: ValueStatus;
};

export type EventPage = {
	items: Array<EventSummaryView>;
	next_cursor: OpaqueCursor | null;
	next_cursor_status: ValueStatus;
};

export type EventVersionPage = {
	items: Array<EventVersionView>;
	next_cursor: OpaqueCursor | null;
	next_cursor_status: ValueStatus;
};

export type NotificationPage = {
	items: Array<NotificationView>;
	next_cursor: OpaqueCursor | null;
	next_cursor_status: ValueStatus;
};

export type AuditPage = {
	items: Array<AuditView>;
	next_cursor: OpaqueCursor | null;
	next_cursor_status: ValueStatus;
};

export type HomeOverviewView = {
	overview_as_of_time: Rfc3339Time | null;
	overview_as_of_time_status: ValueStatus;
	is_partial: boolean;
	stale_sections: Array<string>;
	market_view: MarketView | null;
	market_view_status: ValueStatus;
	risk_items: Array<EventSummaryView>;
	watch_items: Array<EventSummaryView>;
	system_health: SystemHealthSummaryView;
};

export type LoginRequest = {
	username: string;
	password: string;
};

export type LoginView = {
	role: "OWNER";
	expires_at: Rfc3339Time;
};

export type SessionView = {
	role: "OWNER";
	expires_at: Rfc3339Time;
};

export type AnalysisQueryRequest = {
	subject_uid: StableUid;
};

export type AnalysisQueryView = {
	query_uid: StableUid;
	subject_uid: StableUid;
	source_snapshot_uid: StableUid;
	query_snapshot_uid: StableUid;
	evaluation_disposition: "USER_QUERY";
	official_state_unchanged: true;
	as_of_time: Rfc3339Time;
	availability_state: AvailabilityState;
	lifecycle_state: LifecycleState | null;
	lifecycle_value_status: ValueStatus;
	confidence: ConfidenceView;
	data_limitations: Array<DataLimitationView>;
	guardian: GuardianView;
	scout: ScoutView;
	explanation: ExplanationView;
};

export type SectorMatchRequest = {
	query: string;
};

export type SectorMatchCandidateView = {
	sector_uid: StableUid;
	sector_kind: string;
	name: string;
	subject_uid: StableUid | null;
	subject_uid_status: ValueStatus;
};

export type SectorMatchView = {
	query: string;
	match_status: "EXACT" | "NONE" | "AMBIGUOUS";
	selected: SectorMatchCandidateView | null;
	selected_value_status: ValueStatus;
	candidates: Array<SectorMatchCandidateView>;
};

export type NotificationSettingsRequest = {
	enabled: boolean;
};

export type NotificationSettingsView = {
	enabled: boolean;
	endpoint_source: string;
	endpoint_status: "CONFIGURED" | "NOT_CONFIGURED";
	endpoint_masked: string | null;
	endpoint_value_status: ValueStatus;
	updated_at: Rfc3339Time;
	version: number;
	etag: ETagValue;
};

export type BackupView = {
	backup_uid: StableUid;
	sha256: string;
	size_bytes: number;
	created_at: Rfc3339Time;
	verified: true;
};

export type DiagnosticsView = {
	sqlite_version: string;
	journal_mode: string;
	synchronous: number;
	foreign_keys: number;
	auto_vacuum: number;
	wal_autocheckpoint: number;
	integrity_check: string;
	migration_revision: string;
	migration_checksum_valid: boolean;
	artifact_count: number;
	expired_lease_count: number;
	sector_subject_mapping_missing_count: number;
};

export type ErrorView = {
	code: string;
	message: string;
	request_id: string;
};

export interface components {
	schemas: {
		StableUid: StableUid;
		Rfc3339Time: Rfc3339Time;
		CalendarDate: CalendarDate;
		Ratio: Ratio;
		DecimalString: DecimalString;
		OpaqueCursor: OpaqueCursor;
		ETagValue: ETagValue;
		ValueStatus: ValueStatus;
		AvailabilityState: AvailabilityState;
		LifecycleState: LifecycleState;
		DataHealthStatus: DataHealthStatus;
		FitnessStatus: FitnessStatus;
		EvidenceSufficiency: EvidenceSufficiency;
		GuardianEffect: GuardianEffect;
		EventStatus: EventStatus;
		DeliveryStatus: DeliveryStatus;
		HealthLiveView: HealthLiveView;
		SystemHealthSummaryView: SystemHealthSummaryView;
		CapabilityHealthView: CapabilityHealthView;
		CapabilityListView: CapabilityListView;
		EnumRegistryView: EnumRegistryView;
		CodeView: CodeView;
		CodeListView: CodeListView;
		ConfidenceView: ConfidenceView;
		EvidenceItemView: EvidenceItemView;
		GuardianView: GuardianView;
		ScoutView: ScoutView;
		ExplanationView: ExplanationView;
		DataLimitationView: DataLimitationView;
		DataQualityView: DataQualityView;
		LastValidStateView: LastValidStateView;
		MarketSourceView: MarketSourceView;
		MarketView: MarketView;
		InstrumentView: InstrumentView;
		SectorView: SectorView;
		SectorMemberView: SectorMemberView;
		StateTransitionView: StateTransitionView;
		FactView: FactView;
		EventSummaryView: EventSummaryView;
		EventDetailView: EventDetailView;
		EventVersionView: EventVersionView;
		FrozenRiskView: FrozenRiskView;
		FrozenGuardianView: FrozenGuardianView;
		FrozenScoutTagView: FrozenScoutTagView;
		FrozenScoutView: FrozenScoutView;
		FrozenEventView: FrozenEventView;
		NotificationFrozenContextView: NotificationFrozenContextView;
		NotificationView: NotificationView;
		AuditView: AuditView;
		InstrumentPage: InstrumentPage;
		SectorPage: SectorPage;
		SectorMemberPage: SectorMemberPage;
		StateTransitionPage: StateTransitionPage;
		FactPage: FactPage;
		EventPage: EventPage;
		EventVersionPage: EventVersionPage;
		NotificationPage: NotificationPage;
		AuditPage: AuditPage;
		HomeOverviewView: HomeOverviewView;
		LoginRequest: LoginRequest;
		LoginView: LoginView;
		SessionView: SessionView;
		AnalysisQueryRequest: AnalysisQueryRequest;
		AnalysisQueryView: AnalysisQueryView;
		SectorMatchRequest: SectorMatchRequest;
		SectorMatchCandidateView: SectorMatchCandidateView;
		SectorMatchView: SectorMatchView;
		NotificationSettingsRequest: NotificationSettingsRequest;
		NotificationSettingsView: NotificationSettingsView;
		BackupView: BackupView;
		DiagnosticsView: DiagnosticsView;
		ErrorView: ErrorView;
	};
}

export interface OperationRequests {
	healthLive: {
		path: never;
		query: never;
		header: {
			"If-None-Match"?: ETagValue;
		};
		cookie: never;
		body: never;
	};
	healthReady: {
		path: never;
		query: never;
		header: {
			"If-None-Match"?: ETagValue;
		};
		cookie: never;
		body: never;
	};
	ownerLogin: {
		path: never;
		query: never;
		header: never;
		cookie: never;
		body: LoginRequest;
	};
	ownerLogout: {
		path: never;
		query: never;
		header: {
			"X-CSRF-Token": string;
		};
		cookie: never;
		body: never;
	};
	ownerSession: {
		path: never;
		query: never;
		header: never;
		cookie: never;
		body: never;
	};
	systemStatus: {
		path: never;
		query: never;
		header: {
			"If-None-Match"?: ETagValue;
		};
		cookie: never;
		body: never;
	};
	systemCapabilities: {
		path: never;
		query: never;
		header: {
			"If-None-Match"?: ETagValue;
		};
		cookie: never;
		body: never;
	};
	systemIncidents: {
		path: never;
		query: never;
		header: {
			"If-None-Match"?: ETagValue;
		};
		cookie: never;
		body: never;
	};
	metaEnums: {
		path: never;
		query: never;
		header: {
			"If-None-Match"?: ETagValue;
		};
		cookie: never;
		body: never;
	};
	metaCodes: {
		path: {
			group: string;
		};
		query: never;
		header: {
			"If-None-Match"?: ETagValue;
		};
		cookie: never;
		body: never;
	};
	homeOverview: {
		path: never;
		query: never;
		header: {
			"If-None-Match"?: ETagValue;
		};
		cookie: never;
		body: never;
	};
	listInstruments: {
		path: never;
		query: {
			cursor?: OpaqueCursor;
		};
		header: {
			"If-None-Match"?: ETagValue;
		};
		cookie: never;
		body: never;
	};
	getInstrument: {
		path: {
			id: StableUid;
		};
		query: never;
		header: {
			"If-None-Match"?: ETagValue;
		};
		cookie: never;
		body: never;
	};
	listSectors: {
		path: never;
		query: {
			cursor?: OpaqueCursor;
		};
		header: {
			"If-None-Match"?: ETagValue;
		};
		cookie: never;
		body: never;
	};
	getSector: {
		path: {
			id: StableUid;
		};
		query: never;
		header: {
			"If-None-Match"?: ETagValue;
		};
		cookie: never;
		body: never;
	};
	sectorMembers: {
		path: {
			id: StableUid;
		};
		query: {
			cursor?: OpaqueCursor;
		};
		header: {
			"If-None-Match"?: ETagValue;
		};
		cookie: never;
		body: never;
	};
	subjectState: {
		path: {
			id: StableUid;
		};
		query: never;
		header: {
			"If-None-Match"?: ETagValue;
		};
		cookie: never;
		body: never;
	};
	subjectTransitions: {
		path: {
			id: StableUid;
		};
		query: {
			cursor?: OpaqueCursor;
		};
		header: {
			"If-None-Match"?: ETagValue;
		};
		cookie: never;
		body: never;
	};
	subjectFacts: {
		path: {
			id: StableUid;
		};
		query: {
			cursor?: OpaqueCursor;
		};
		header: {
			"If-None-Match"?: ETagValue;
		};
		cookie: never;
		body: never;
	};
	listEvents: {
		path: never;
		query: {
			cursor?: OpaqueCursor;
		};
		header: {
			"If-None-Match"?: ETagValue;
		};
		cookie: never;
		body: never;
	};
	getEvent: {
		path: {
			id: StableUid;
		};
		query: never;
		header: {
			"If-None-Match"?: ETagValue;
		};
		cookie: never;
		body: never;
	};
	eventVersions: {
		path: {
			id: StableUid;
		};
		query: {
			cursor?: OpaqueCursor;
		};
		header: {
			"If-None-Match"?: ETagValue;
		};
		cookie: never;
		body: never;
	};
	createAnalysisQuery: {
		path: never;
		query: never;
		header: {
			"X-CSRF-Token": string;
			"Idempotency-Key": string;
		};
		cookie: never;
		body: AnalysisQueryRequest;
	};
	sectorMatch: {
		path: never;
		query: never;
		header: never;
		cookie: never;
		body: SectorMatchRequest;
	};
	listNotifications: {
		path: never;
		query: {
			cursor?: OpaqueCursor;
		};
		header: {
			"If-None-Match"?: ETagValue;
		};
		cookie: never;
		body: never;
	};
	getNotification: {
		path: {
			id: StableUid;
		};
		query: never;
		header: {
			"If-None-Match"?: ETagValue;
		};
		cookie: never;
		body: never;
	};
	notificationSettings: {
		path: never;
		query: never;
		header: never;
		cookie: never;
		body: never;
	};
	updateNotificationSettings: {
		path: never;
		query: never;
		header: {
			"If-Match": ETagValue;
			"X-CSRF-Token": string;
			"Idempotency-Key": string;
		};
		cookie: never;
		body: NotificationSettingsRequest;
	};
	createBackup: {
		path: never;
		query: never;
		header: {
			"X-CSRF-Token": string;
			"Idempotency-Key": string;
		};
		cookie: never;
		body: never;
	};
	diagnostics: {
		path: never;
		query: never;
		header: never;
		cookie: never;
		body: never;
	};
	auditRecords: {
		path: never;
		query: {
			cursor?: OpaqueCursor;
		};
		header: never;
		cookie: never;
		body: never;
	};
}

export interface OperationResponses {
	healthLive: {
		"200": {
			headers: {
				"Cache-Control": "private, no-cache";
				ETag: ETagValue;
				"X-Request-ID": string;
			};
			body: HealthLiveView;
		};
		"304": {
			headers: {
				"Cache-Control": "private, no-cache";
				ETag: ETagValue;
				"X-Request-ID": string;
			};
			body: never;
		};
		"500": {
			headers: {
				"Cache-Control": "no-store";
				"X-Request-ID": string;
			};
			body: ErrorView;
		};
	};
	healthReady: {
		"200": {
			headers: {
				"Cache-Control": "private, no-cache";
				ETag: ETagValue;
				"X-Request-ID": string;
			};
			body: SystemHealthSummaryView;
		};
		"304": {
			headers: {
				"Cache-Control": "private, no-cache";
				ETag: ETagValue;
				"X-Request-ID": string;
			};
			body: never;
		};
		"503": {
			headers: {
				"Cache-Control": "no-store";
				"X-Request-ID": string;
			};
			body: ErrorView;
		};
		"500": {
			headers: {
				"Cache-Control": "no-store";
				"X-Request-ID": string;
			};
			body: ErrorView;
		};
	};
	ownerLogin: {
		"200": {
			headers: {
				"Cache-Control": "no-store";
				"Set-Cookie": string;
				"X-CSRF-Token": string;
				"X-Request-ID": string;
			};
			body: LoginView;
		};
		"400": {
			headers: {
				"Cache-Control": "no-store";
				"X-Request-ID": string;
			};
			body: ErrorView;
		};
		"401": {
			headers: {
				"Cache-Control": "no-store";
				"X-Request-ID": string;
			};
			body: ErrorView;
		};
		"429": {
			headers: {
				"Cache-Control": "no-store";
				"X-Request-ID": string;
			};
			body: ErrorView;
		};
		"503": {
			headers: {
				"Cache-Control": "no-store";
				"X-Request-ID": string;
			};
			body: ErrorView;
		};
		"500": {
			headers: {
				"Cache-Control": "no-store";
				"X-Request-ID": string;
			};
			body: ErrorView;
		};
	};
	ownerLogout: {
		"204": {
			headers: {
				"Cache-Control": "no-store";
				"Set-Cookie": string;
				"X-Request-ID": string;
			};
			body: never;
		};
		"401": {
			headers: {
				"Cache-Control": "no-store";
				"X-Request-ID": string;
			};
			body: ErrorView;
		};
		"403": {
			headers: {
				"Cache-Control": "no-store";
				"X-Request-ID": string;
			};
			body: ErrorView;
		};
		"503": {
			headers: {
				"Cache-Control": "no-store";
				"X-Request-ID": string;
			};
			body: ErrorView;
		};
		"500": {
			headers: {
				"Cache-Control": "no-store";
				"X-Request-ID": string;
			};
			body: ErrorView;
		};
	};
	ownerSession: {
		"200": {
			headers: {
				"Cache-Control": "no-store";
				"X-Request-ID": string;
			};
			body: SessionView;
		};
		"401": {
			headers: {
				"Cache-Control": "no-store";
				"X-Request-ID": string;
			};
			body: ErrorView;
		};
		"503": {
			headers: {
				"Cache-Control": "no-store";
				"X-Request-ID": string;
			};
			body: ErrorView;
		};
		"500": {
			headers: {
				"Cache-Control": "no-store";
				"X-Request-ID": string;
			};
			body: ErrorView;
		};
	};
	systemStatus: {
		"200": {
			headers: {
				"Cache-Control": "private, no-cache";
				ETag: ETagValue;
				"X-Request-ID": string;
			};
			body: SystemHealthSummaryView;
		};
		"304": {
			headers: {
				"Cache-Control": "private, no-cache";
				ETag: ETagValue;
				"X-Request-ID": string;
			};
			body: never;
		};
		"503": {
			headers: {
				"Cache-Control": "no-store";
				"X-Request-ID": string;
			};
			body: ErrorView;
		};
		"500": {
			headers: {
				"Cache-Control": "no-store";
				"X-Request-ID": string;
			};
			body: ErrorView;
		};
	};
	systemCapabilities: {
		"200": {
			headers: {
				"Cache-Control": "private, no-cache";
				ETag: ETagValue;
				"X-Request-ID": string;
			};
			body: CapabilityListView;
		};
		"304": {
			headers: {
				"Cache-Control": "private, no-cache";
				ETag: ETagValue;
				"X-Request-ID": string;
			};
			body: never;
		};
		"503": {
			headers: {
				"Cache-Control": "no-store";
				"X-Request-ID": string;
			};
			body: ErrorView;
		};
		"500": {
			headers: {
				"Cache-Control": "no-store";
				"X-Request-ID": string;
			};
			body: ErrorView;
		};
	};
	systemIncidents: {
		"200": {
			headers: {
				"Cache-Control": "private, no-cache";
				ETag: ETagValue;
				"X-Request-ID": string;
			};
			body: CapabilityListView;
		};
		"304": {
			headers: {
				"Cache-Control": "private, no-cache";
				ETag: ETagValue;
				"X-Request-ID": string;
			};
			body: never;
		};
		"503": {
			headers: {
				"Cache-Control": "no-store";
				"X-Request-ID": string;
			};
			body: ErrorView;
		};
		"500": {
			headers: {
				"Cache-Control": "no-store";
				"X-Request-ID": string;
			};
			body: ErrorView;
		};
	};
	metaEnums: {
		"200": {
			headers: {
				"Cache-Control": "private, no-cache";
				ETag: ETagValue;
				"X-Request-ID": string;
			};
			body: EnumRegistryView;
		};
		"304": {
			headers: {
				"Cache-Control": "private, no-cache";
				ETag: ETagValue;
				"X-Request-ID": string;
			};
			body: never;
		};
		"503": {
			headers: {
				"Cache-Control": "no-store";
				"X-Request-ID": string;
			};
			body: ErrorView;
		};
		"500": {
			headers: {
				"Cache-Control": "no-store";
				"X-Request-ID": string;
			};
			body: ErrorView;
		};
	};
	metaCodes: {
		"200": {
			headers: {
				"Cache-Control": "private, no-cache";
				ETag: ETagValue;
				"X-Request-ID": string;
			};
			body: CodeListView;
		};
		"304": {
			headers: {
				"Cache-Control": "private, no-cache";
				ETag: ETagValue;
				"X-Request-ID": string;
			};
			body: never;
		};
		"400": {
			headers: {
				"Cache-Control": "no-store";
				"X-Request-ID": string;
			};
			body: ErrorView;
		};
		"503": {
			headers: {
				"Cache-Control": "no-store";
				"X-Request-ID": string;
			};
			body: ErrorView;
		};
		"500": {
			headers: {
				"Cache-Control": "no-store";
				"X-Request-ID": string;
			};
			body: ErrorView;
		};
	};
	homeOverview: {
		"200": {
			headers: {
				"Cache-Control": "private, no-cache";
				ETag: ETagValue;
				"X-Request-ID": string;
			};
			body: HomeOverviewView;
		};
		"304": {
			headers: {
				"Cache-Control": "private, no-cache";
				ETag: ETagValue;
				"X-Request-ID": string;
			};
			body: never;
		};
		"503": {
			headers: {
				"Cache-Control": "no-store";
				"X-Request-ID": string;
			};
			body: ErrorView;
		};
		"500": {
			headers: {
				"Cache-Control": "no-store";
				"X-Request-ID": string;
			};
			body: ErrorView;
		};
	};
	listInstruments: {
		"200": {
			headers: {
				"Cache-Control": "private, no-cache";
				ETag: ETagValue;
				"X-Request-ID": string;
			};
			body: InstrumentPage;
		};
		"304": {
			headers: {
				"Cache-Control": "private, no-cache";
				ETag: ETagValue;
				"X-Request-ID": string;
			};
			body: never;
		};
		"400": {
			headers: {
				"Cache-Control": "no-store";
				"X-Request-ID": string;
			};
			body: ErrorView;
		};
		"503": {
			headers: {
				"Cache-Control": "no-store";
				"X-Request-ID": string;
			};
			body: ErrorView;
		};
		"500": {
			headers: {
				"Cache-Control": "no-store";
				"X-Request-ID": string;
			};
			body: ErrorView;
		};
	};
	getInstrument: {
		"200": {
			headers: {
				"Cache-Control": "private, no-cache";
				ETag: ETagValue;
				"X-Request-ID": string;
			};
			body: InstrumentView;
		};
		"304": {
			headers: {
				"Cache-Control": "private, no-cache";
				ETag: ETagValue;
				"X-Request-ID": string;
			};
			body: never;
		};
		"400": {
			headers: {
				"Cache-Control": "no-store";
				"X-Request-ID": string;
			};
			body: ErrorView;
		};
		"404": {
			headers: {
				"Cache-Control": "no-store";
				"X-Request-ID": string;
			};
			body: ErrorView;
		};
		"503": {
			headers: {
				"Cache-Control": "no-store";
				"X-Request-ID": string;
			};
			body: ErrorView;
		};
		"500": {
			headers: {
				"Cache-Control": "no-store";
				"X-Request-ID": string;
			};
			body: ErrorView;
		};
	};
	listSectors: {
		"200": {
			headers: {
				"Cache-Control": "private, no-cache";
				ETag: ETagValue;
				"X-Request-ID": string;
			};
			body: SectorPage;
		};
		"304": {
			headers: {
				"Cache-Control": "private, no-cache";
				ETag: ETagValue;
				"X-Request-ID": string;
			};
			body: never;
		};
		"400": {
			headers: {
				"Cache-Control": "no-store";
				"X-Request-ID": string;
			};
			body: ErrorView;
		};
		"503": {
			headers: {
				"Cache-Control": "no-store";
				"X-Request-ID": string;
			};
			body: ErrorView;
		};
		"500": {
			headers: {
				"Cache-Control": "no-store";
				"X-Request-ID": string;
			};
			body: ErrorView;
		};
	};
	getSector: {
		"200": {
			headers: {
				"Cache-Control": "private, no-cache";
				ETag: ETagValue;
				"X-Request-ID": string;
			};
			body: SectorView;
		};
		"304": {
			headers: {
				"Cache-Control": "private, no-cache";
				ETag: ETagValue;
				"X-Request-ID": string;
			};
			body: never;
		};
		"400": {
			headers: {
				"Cache-Control": "no-store";
				"X-Request-ID": string;
			};
			body: ErrorView;
		};
		"404": {
			headers: {
				"Cache-Control": "no-store";
				"X-Request-ID": string;
			};
			body: ErrorView;
		};
		"503": {
			headers: {
				"Cache-Control": "no-store";
				"X-Request-ID": string;
			};
			body: ErrorView;
		};
		"500": {
			headers: {
				"Cache-Control": "no-store";
				"X-Request-ID": string;
			};
			body: ErrorView;
		};
	};
	sectorMembers: {
		"200": {
			headers: {
				"Cache-Control": "private, no-cache";
				ETag: ETagValue;
				"X-Request-ID": string;
			};
			body: SectorMemberPage;
		};
		"304": {
			headers: {
				"Cache-Control": "private, no-cache";
				ETag: ETagValue;
				"X-Request-ID": string;
			};
			body: never;
		};
		"400": {
			headers: {
				"Cache-Control": "no-store";
				"X-Request-ID": string;
			};
			body: ErrorView;
		};
		"404": {
			headers: {
				"Cache-Control": "no-store";
				"X-Request-ID": string;
			};
			body: ErrorView;
		};
		"503": {
			headers: {
				"Cache-Control": "no-store";
				"X-Request-ID": string;
			};
			body: ErrorView;
		};
		"500": {
			headers: {
				"Cache-Control": "no-store";
				"X-Request-ID": string;
			};
			body: ErrorView;
		};
	};
	subjectState: {
		"200": {
			headers: {
				"Cache-Control": "private, no-cache";
				ETag: ETagValue;
				"X-Request-ID": string;
			};
			body: MarketView;
		};
		"304": {
			headers: {
				"Cache-Control": "private, no-cache";
				ETag: ETagValue;
				"X-Request-ID": string;
			};
			body: never;
		};
		"400": {
			headers: {
				"Cache-Control": "no-store";
				"X-Request-ID": string;
			};
			body: ErrorView;
		};
		"404": {
			headers: {
				"Cache-Control": "no-store";
				"X-Request-ID": string;
			};
			body: ErrorView;
		};
		"503": {
			headers: {
				"Cache-Control": "no-store";
				"X-Request-ID": string;
			};
			body: ErrorView;
		};
		"500": {
			headers: {
				"Cache-Control": "no-store";
				"X-Request-ID": string;
			};
			body: ErrorView;
		};
	};
	subjectTransitions: {
		"200": {
			headers: {
				"Cache-Control": "private, no-cache";
				ETag: ETagValue;
				"X-Request-ID": string;
			};
			body: StateTransitionPage;
		};
		"304": {
			headers: {
				"Cache-Control": "private, no-cache";
				ETag: ETagValue;
				"X-Request-ID": string;
			};
			body: never;
		};
		"400": {
			headers: {
				"Cache-Control": "no-store";
				"X-Request-ID": string;
			};
			body: ErrorView;
		};
		"404": {
			headers: {
				"Cache-Control": "no-store";
				"X-Request-ID": string;
			};
			body: ErrorView;
		};
		"503": {
			headers: {
				"Cache-Control": "no-store";
				"X-Request-ID": string;
			};
			body: ErrorView;
		};
		"500": {
			headers: {
				"Cache-Control": "no-store";
				"X-Request-ID": string;
			};
			body: ErrorView;
		};
	};
	subjectFacts: {
		"200": {
			headers: {
				"Cache-Control": "private, no-cache";
				ETag: ETagValue;
				"X-Request-ID": string;
			};
			body: FactPage;
		};
		"304": {
			headers: {
				"Cache-Control": "private, no-cache";
				ETag: ETagValue;
				"X-Request-ID": string;
			};
			body: never;
		};
		"400": {
			headers: {
				"Cache-Control": "no-store";
				"X-Request-ID": string;
			};
			body: ErrorView;
		};
		"404": {
			headers: {
				"Cache-Control": "no-store";
				"X-Request-ID": string;
			};
			body: ErrorView;
		};
		"503": {
			headers: {
				"Cache-Control": "no-store";
				"X-Request-ID": string;
			};
			body: ErrorView;
		};
		"500": {
			headers: {
				"Cache-Control": "no-store";
				"X-Request-ID": string;
			};
			body: ErrorView;
		};
	};
	listEvents: {
		"200": {
			headers: {
				"Cache-Control": "private, no-cache";
				ETag: ETagValue;
				"X-Request-ID": string;
			};
			body: EventPage;
		};
		"304": {
			headers: {
				"Cache-Control": "private, no-cache";
				ETag: ETagValue;
				"X-Request-ID": string;
			};
			body: never;
		};
		"400": {
			headers: {
				"Cache-Control": "no-store";
				"X-Request-ID": string;
			};
			body: ErrorView;
		};
		"503": {
			headers: {
				"Cache-Control": "no-store";
				"X-Request-ID": string;
			};
			body: ErrorView;
		};
		"500": {
			headers: {
				"Cache-Control": "no-store";
				"X-Request-ID": string;
			};
			body: ErrorView;
		};
	};
	getEvent: {
		"200": {
			headers: {
				"Cache-Control": "private, no-cache";
				ETag: ETagValue;
				"X-Request-ID": string;
			};
			body: EventDetailView;
		};
		"304": {
			headers: {
				"Cache-Control": "private, no-cache";
				ETag: ETagValue;
				"X-Request-ID": string;
			};
			body: never;
		};
		"400": {
			headers: {
				"Cache-Control": "no-store";
				"X-Request-ID": string;
			};
			body: ErrorView;
		};
		"404": {
			headers: {
				"Cache-Control": "no-store";
				"X-Request-ID": string;
			};
			body: ErrorView;
		};
		"503": {
			headers: {
				"Cache-Control": "no-store";
				"X-Request-ID": string;
			};
			body: ErrorView;
		};
		"500": {
			headers: {
				"Cache-Control": "no-store";
				"X-Request-ID": string;
			};
			body: ErrorView;
		};
	};
	eventVersions: {
		"200": {
			headers: {
				"Cache-Control": "private, no-cache";
				ETag: ETagValue;
				"X-Request-ID": string;
			};
			body: EventVersionPage;
		};
		"304": {
			headers: {
				"Cache-Control": "private, no-cache";
				ETag: ETagValue;
				"X-Request-ID": string;
			};
			body: never;
		};
		"400": {
			headers: {
				"Cache-Control": "no-store";
				"X-Request-ID": string;
			};
			body: ErrorView;
		};
		"404": {
			headers: {
				"Cache-Control": "no-store";
				"X-Request-ID": string;
			};
			body: ErrorView;
		};
		"503": {
			headers: {
				"Cache-Control": "no-store";
				"X-Request-ID": string;
			};
			body: ErrorView;
		};
		"500": {
			headers: {
				"Cache-Control": "no-store";
				"X-Request-ID": string;
			};
			body: ErrorView;
		};
	};
	createAnalysisQuery: {
		"200": {
			headers: {
				"Cache-Control": "no-store";
				"X-Request-ID": string;
			};
			body: AnalysisQueryView;
		};
		"400": {
			headers: {
				"Cache-Control": "no-store";
				"X-Request-ID": string;
			};
			body: ErrorView;
		};
		"401": {
			headers: {
				"Cache-Control": "no-store";
				"X-Request-ID": string;
			};
			body: ErrorView;
		};
		"403": {
			headers: {
				"Cache-Control": "no-store";
				"X-Request-ID": string;
			};
			body: ErrorView;
		};
		"404": {
			headers: {
				"Cache-Control": "no-store";
				"X-Request-ID": string;
			};
			body: ErrorView;
		};
		"409": {
			headers: {
				"Cache-Control": "no-store";
				"X-Request-ID": string;
			};
			body: ErrorView;
		};
		"429": {
			headers: {
				"Cache-Control": "no-store";
				"X-Request-ID": string;
			};
			body: ErrorView;
		};
		"503": {
			headers: {
				"Cache-Control": "no-store";
				"X-Request-ID": string;
			};
			body: ErrorView;
		};
		"500": {
			headers: {
				"Cache-Control": "no-store";
				"X-Request-ID": string;
			};
			body: ErrorView;
		};
	};
	sectorMatch: {
		"200": {
			headers: {
				"Cache-Control": "no-store";
				"X-Request-ID": string;
			};
			body: SectorMatchView;
		};
		"400": {
			headers: {
				"Cache-Control": "no-store";
				"X-Request-ID": string;
			};
			body: ErrorView;
		};
		"401": {
			headers: {
				"Cache-Control": "no-store";
				"X-Request-ID": string;
			};
			body: ErrorView;
		};
		"503": {
			headers: {
				"Cache-Control": "no-store";
				"X-Request-ID": string;
			};
			body: ErrorView;
		};
		"500": {
			headers: {
				"Cache-Control": "no-store";
				"X-Request-ID": string;
			};
			body: ErrorView;
		};
	};
	listNotifications: {
		"200": {
			headers: {
				"Cache-Control": "private, no-cache";
				ETag: ETagValue;
				"X-Request-ID": string;
			};
			body: NotificationPage;
		};
		"304": {
			headers: {
				"Cache-Control": "private, no-cache";
				ETag: ETagValue;
				"X-Request-ID": string;
			};
			body: never;
		};
		"400": {
			headers: {
				"Cache-Control": "no-store";
				"X-Request-ID": string;
			};
			body: ErrorView;
		};
		"503": {
			headers: {
				"Cache-Control": "no-store";
				"X-Request-ID": string;
			};
			body: ErrorView;
		};
		"500": {
			headers: {
				"Cache-Control": "no-store";
				"X-Request-ID": string;
			};
			body: ErrorView;
		};
	};
	getNotification: {
		"200": {
			headers: {
				"Cache-Control": "private, no-cache";
				ETag: ETagValue;
				"X-Request-ID": string;
			};
			body: NotificationView;
		};
		"304": {
			headers: {
				"Cache-Control": "private, no-cache";
				ETag: ETagValue;
				"X-Request-ID": string;
			};
			body: never;
		};
		"400": {
			headers: {
				"Cache-Control": "no-store";
				"X-Request-ID": string;
			};
			body: ErrorView;
		};
		"404": {
			headers: {
				"Cache-Control": "no-store";
				"X-Request-ID": string;
			};
			body: ErrorView;
		};
		"503": {
			headers: {
				"Cache-Control": "no-store";
				"X-Request-ID": string;
			};
			body: ErrorView;
		};
		"500": {
			headers: {
				"Cache-Control": "no-store";
				"X-Request-ID": string;
			};
			body: ErrorView;
		};
	};
	notificationSettings: {
		"200": {
			headers: {
				"Cache-Control": "no-store";
				ETag: ETagValue;
				"X-Request-ID": string;
			};
			body: NotificationSettingsView;
		};
		"401": {
			headers: {
				"Cache-Control": "no-store";
				"X-Request-ID": string;
			};
			body: ErrorView;
		};
		"503": {
			headers: {
				"Cache-Control": "no-store";
				"X-Request-ID": string;
			};
			body: ErrorView;
		};
		"500": {
			headers: {
				"Cache-Control": "no-store";
				"X-Request-ID": string;
			};
			body: ErrorView;
		};
	};
	updateNotificationSettings: {
		"200": {
			headers: {
				"Cache-Control": "no-store";
				ETag: ETagValue;
				"X-Request-ID": string;
			};
			body: NotificationSettingsView;
		};
		"400": {
			headers: {
				"Cache-Control": "no-store";
				"X-Request-ID": string;
			};
			body: ErrorView;
		};
		"401": {
			headers: {
				"Cache-Control": "no-store";
				"X-Request-ID": string;
			};
			body: ErrorView;
		};
		"403": {
			headers: {
				"Cache-Control": "no-store";
				"X-Request-ID": string;
			};
			body: ErrorView;
		};
		"409": {
			headers: {
				"Cache-Control": "no-store";
				"X-Request-ID": string;
			};
			body: ErrorView;
		};
		"503": {
			headers: {
				"Cache-Control": "no-store";
				"X-Request-ID": string;
			};
			body: ErrorView;
		};
		"500": {
			headers: {
				"Cache-Control": "no-store";
				"X-Request-ID": string;
			};
			body: ErrorView;
		};
	};
	createBackup: {
		"201": {
			headers: {
				"Cache-Control": "no-store";
				"X-Request-ID": string;
			};
			body: BackupView;
		};
		"400": {
			headers: {
				"Cache-Control": "no-store";
				"X-Request-ID": string;
			};
			body: ErrorView;
		};
		"401": {
			headers: {
				"Cache-Control": "no-store";
				"X-Request-ID": string;
			};
			body: ErrorView;
		};
		"403": {
			headers: {
				"Cache-Control": "no-store";
				"X-Request-ID": string;
			};
			body: ErrorView;
		};
		"409": {
			headers: {
				"Cache-Control": "no-store";
				"X-Request-ID": string;
			};
			body: ErrorView;
		};
		"503": {
			headers: {
				"Cache-Control": "no-store";
				"X-Request-ID": string;
			};
			body: ErrorView;
		};
		"500": {
			headers: {
				"Cache-Control": "no-store";
				"X-Request-ID": string;
			};
			body: ErrorView;
		};
	};
	diagnostics: {
		"200": {
			headers: {
				"Cache-Control": "no-store";
				"X-Request-ID": string;
			};
			body: DiagnosticsView;
		};
		"401": {
			headers: {
				"Cache-Control": "no-store";
				"X-Request-ID": string;
			};
			body: ErrorView;
		};
		"503": {
			headers: {
				"Cache-Control": "no-store";
				"X-Request-ID": string;
			};
			body: ErrorView;
		};
		"500": {
			headers: {
				"Cache-Control": "no-store";
				"X-Request-ID": string;
			};
			body: ErrorView;
		};
	};
	auditRecords: {
		"200": {
			headers: {
				"Cache-Control": "no-store";
				"X-Request-ID": string;
			};
			body: AuditPage;
		};
		"400": {
			headers: {
				"Cache-Control": "no-store";
				"X-Request-ID": string;
			};
			body: ErrorView;
		};
		"401": {
			headers: {
				"Cache-Control": "no-store";
				"X-Request-ID": string;
			};
			body: ErrorView;
		};
		"503": {
			headers: {
				"Cache-Control": "no-store";
				"X-Request-ID": string;
			};
			body: ErrorView;
		};
		"500": {
			headers: {
				"Cache-Control": "no-store";
				"X-Request-ID": string;
			};
			body: ErrorView;
		};
	};
}

export interface ApiOperations {
	healthLive: {
		method: "GET";
		path: "/health/live";
		request: OperationRequests["healthLive"];
		responses: OperationResponses["healthLive"];
	};
	healthReady: {
		method: "GET";
		path: "/health/ready";
		request: OperationRequests["healthReady"];
		responses: OperationResponses["healthReady"];
	};
	ownerLogin: {
		method: "POST";
		path: "/api/v1/auth/login";
		request: OperationRequests["ownerLogin"];
		responses: OperationResponses["ownerLogin"];
	};
	ownerLogout: {
		method: "POST";
		path: "/api/v1/auth/logout";
		request: OperationRequests["ownerLogout"];
		responses: OperationResponses["ownerLogout"];
	};
	ownerSession: {
		method: "GET";
		path: "/api/v1/auth/session";
		request: OperationRequests["ownerSession"];
		responses: OperationResponses["ownerSession"];
	};
	systemStatus: {
		method: "GET";
		path: "/api/v1/system/status";
		request: OperationRequests["systemStatus"];
		responses: OperationResponses["systemStatus"];
	};
	systemCapabilities: {
		method: "GET";
		path: "/api/v1/system/capabilities";
		request: OperationRequests["systemCapabilities"];
		responses: OperationResponses["systemCapabilities"];
	};
	systemIncidents: {
		method: "GET";
		path: "/api/v1/system/incidents";
		request: OperationRequests["systemIncidents"];
		responses: OperationResponses["systemIncidents"];
	};
	metaEnums: {
		method: "GET";
		path: "/api/v1/meta/enums";
		request: OperationRequests["metaEnums"];
		responses: OperationResponses["metaEnums"];
	};
	metaCodes: {
		method: "GET";
		path: "/api/v1/meta/codes/{group}";
		request: OperationRequests["metaCodes"];
		responses: OperationResponses["metaCodes"];
	};
	homeOverview: {
		method: "GET";
		path: "/api/v1/home/overview";
		request: OperationRequests["homeOverview"];
		responses: OperationResponses["homeOverview"];
	};
	listInstruments: {
		method: "GET";
		path: "/api/v1/instruments";
		request: OperationRequests["listInstruments"];
		responses: OperationResponses["listInstruments"];
	};
	getInstrument: {
		method: "GET";
		path: "/api/v1/instruments/{id}";
		request: OperationRequests["getInstrument"];
		responses: OperationResponses["getInstrument"];
	};
	listSectors: {
		method: "GET";
		path: "/api/v1/sectors";
		request: OperationRequests["listSectors"];
		responses: OperationResponses["listSectors"];
	};
	getSector: {
		method: "GET";
		path: "/api/v1/sectors/{id}";
		request: OperationRequests["getSector"];
		responses: OperationResponses["getSector"];
	};
	sectorMembers: {
		method: "GET";
		path: "/api/v1/sectors/{id}/members";
		request: OperationRequests["sectorMembers"];
		responses: OperationResponses["sectorMembers"];
	};
	subjectState: {
		method: "GET";
		path: "/api/v1/subjects/{id}/state";
		request: OperationRequests["subjectState"];
		responses: OperationResponses["subjectState"];
	};
	subjectTransitions: {
		method: "GET";
		path: "/api/v1/subjects/{id}/state-transitions";
		request: OperationRequests["subjectTransitions"];
		responses: OperationResponses["subjectTransitions"];
	};
	subjectFacts: {
		method: "GET";
		path: "/api/v1/subjects/{id}/facts";
		request: OperationRequests["subjectFacts"];
		responses: OperationResponses["subjectFacts"];
	};
	listEvents: {
		method: "GET";
		path: "/api/v1/events";
		request: OperationRequests["listEvents"];
		responses: OperationResponses["listEvents"];
	};
	getEvent: {
		method: "GET";
		path: "/api/v1/events/{id}";
		request: OperationRequests["getEvent"];
		responses: OperationResponses["getEvent"];
	};
	eventVersions: {
		method: "GET";
		path: "/api/v1/events/{id}/versions";
		request: OperationRequests["eventVersions"];
		responses: OperationResponses["eventVersions"];
	};
	createAnalysisQuery: {
		method: "POST";
		path: "/api/v1/analysis/queries";
		request: OperationRequests["createAnalysisQuery"];
		responses: OperationResponses["createAnalysisQuery"];
	};
	sectorMatch: {
		method: "POST";
		path: "/api/v1/analysis/sector-match";
		request: OperationRequests["sectorMatch"];
		responses: OperationResponses["sectorMatch"];
	};
	listNotifications: {
		method: "GET";
		path: "/api/v1/notifications";
		request: OperationRequests["listNotifications"];
		responses: OperationResponses["listNotifications"];
	};
	getNotification: {
		method: "GET";
		path: "/api/v1/notifications/{id}";
		request: OperationRequests["getNotification"];
		responses: OperationResponses["getNotification"];
	};
	notificationSettings: {
		method: "GET";
		path: "/api/v1/settings/notifications";
		request: OperationRequests["notificationSettings"];
		responses: OperationResponses["notificationSettings"];
	};
	updateNotificationSettings: {
		method: "PUT";
		path: "/api/v1/settings/notifications";
		request: OperationRequests["updateNotificationSettings"];
		responses: OperationResponses["updateNotificationSettings"];
	};
	createBackup: {
		method: "POST";
		path: "/api/v1/operations/backups";
		request: OperationRequests["createBackup"];
		responses: OperationResponses["createBackup"];
	};
	diagnostics: {
		method: "GET";
		path: "/api/v1/operations/diagnostics";
		request: OperationRequests["diagnostics"];
		responses: OperationResponses["diagnostics"];
	};
	auditRecords: {
		method: "GET";
		path: "/api/v1/audit";
		request: OperationRequests["auditRecords"];
		responses: OperationResponses["auditRecords"];
	};
}

export interface ApiPaths {
	"/health/live": {
		get: ApiOperations["healthLive"];
	};
	"/health/ready": {
		get: ApiOperations["healthReady"];
	};
	"/api/v1/auth/login": {
		post: ApiOperations["ownerLogin"];
	};
	"/api/v1/auth/logout": {
		post: ApiOperations["ownerLogout"];
	};
	"/api/v1/auth/session": {
		get: ApiOperations["ownerSession"];
	};
	"/api/v1/system/status": {
		get: ApiOperations["systemStatus"];
	};
	"/api/v1/system/capabilities": {
		get: ApiOperations["systemCapabilities"];
	};
	"/api/v1/system/incidents": {
		get: ApiOperations["systemIncidents"];
	};
	"/api/v1/meta/enums": {
		get: ApiOperations["metaEnums"];
	};
	"/api/v1/meta/codes/{group}": {
		get: ApiOperations["metaCodes"];
	};
	"/api/v1/home/overview": {
		get: ApiOperations["homeOverview"];
	};
	"/api/v1/instruments": {
		get: ApiOperations["listInstruments"];
	};
	"/api/v1/instruments/{id}": {
		get: ApiOperations["getInstrument"];
	};
	"/api/v1/sectors": {
		get: ApiOperations["listSectors"];
	};
	"/api/v1/sectors/{id}": {
		get: ApiOperations["getSector"];
	};
	"/api/v1/sectors/{id}/members": {
		get: ApiOperations["sectorMembers"];
	};
	"/api/v1/subjects/{id}/state": {
		get: ApiOperations["subjectState"];
	};
	"/api/v1/subjects/{id}/state-transitions": {
		get: ApiOperations["subjectTransitions"];
	};
	"/api/v1/subjects/{id}/facts": {
		get: ApiOperations["subjectFacts"];
	};
	"/api/v1/events": {
		get: ApiOperations["listEvents"];
	};
	"/api/v1/events/{id}": {
		get: ApiOperations["getEvent"];
	};
	"/api/v1/events/{id}/versions": {
		get: ApiOperations["eventVersions"];
	};
	"/api/v1/analysis/queries": {
		post: ApiOperations["createAnalysisQuery"];
	};
	"/api/v1/analysis/sector-match": {
		post: ApiOperations["sectorMatch"];
	};
	"/api/v1/notifications": {
		get: ApiOperations["listNotifications"];
	};
	"/api/v1/notifications/{id}": {
		get: ApiOperations["getNotification"];
	};
	"/api/v1/settings/notifications": {
		get: ApiOperations["notificationSettings"];
		put: ApiOperations["updateNotificationSettings"];
	};
	"/api/v1/operations/backups": {
		post: ApiOperations["createBackup"];
	};
	"/api/v1/operations/diagnostics": {
		get: ApiOperations["diagnostics"];
	};
	"/api/v1/audit": {
		get: ApiOperations["auditRecords"];
	};
}
